interface HTMLAttributes {
  class?: string
  id?: string
  name?: string
  content?: string
  charset?: string
}

interface IntrinsicElements {
  a: HTMLAttributes
  abbr: HTMLAttributes
  address: HTMLAttributes
  area: HTMLAttributes
  article: HTMLAttributes
  aside: HTMLAttributes
  audio: HTMLAttributes
  b: HTMLAttributes
  base: HTMLAttributes
  bdi: HTMLAttributes
  bdo: HTMLAttributes
  blockquote: HTMLAttributes
  body: HTMLAttributes
  br: HTMLAttributes
  button: HTMLAttributes
  canvas: HTMLAttributes
  caption: HTMLAttributes
  cite: HTMLAttributes
  code: HTMLAttributes
  col: HTMLAttributes
  colgroup: HTMLAttributes
  data: HTMLAttributes
  datalist: HTMLAttributes
  dd: HTMLAttributes
  del: HTMLAttributes
  details: HTMLAttributes
  dfn: HTMLAttributes
  dialog: HTMLAttributes
  div: HTMLAttributes
  dl: HTMLAttributes
  dt: HTMLAttributes
  em: HTMLAttributes
  embed: HTMLAttributes
  fieldset: HTMLAttributes
  figcaption: HTMLAttributes
  figure: HTMLAttributes
  footer: HTMLAttributes
  form: HTMLAttributes
  h1: HTMLAttributes
  h2: HTMLAttributes
  h3: HTMLAttributes
  h4: HTMLAttributes
  h5: HTMLAttributes
  h6: HTMLAttributes
  head: HTMLAttributes
  header: HTMLAttributes
  hgroup: HTMLAttributes
  hr: HTMLAttributes
  html: HTMLAttributes
  i: HTMLAttributes
  iframe: HTMLAttributes
  img: HTMLAttributes
  input: HTMLAttributes
  ins: HTMLAttributes
  kbd: HTMLAttributes
  label: HTMLAttributes
  legend: HTMLAttributes
  li: HTMLAttributes
  link: HTMLAttributes
  main: HTMLAttributes
  map: HTMLAttributes
  mark: HTMLAttributes
  math: HTMLAttributes
  menu: HTMLAttributes
  menuitem: HTMLAttributes
  meta: HTMLAttributes
  meter: HTMLAttributes
  nav: HTMLAttributes
  noscript: HTMLAttributes
  object: HTMLAttributes
  ol: HTMLAttributes
  optgroup: HTMLAttributes
  option: HTMLAttributes
  output: HTMLAttributes
  p: HTMLAttributes
  param: HTMLAttributes
  picture: HTMLAttributes
  pre: HTMLAttributes
  progress: HTMLAttributes
  q: HTMLAttributes
  rb: HTMLAttributes
  rp: HTMLAttributes
  rt: HTMLAttributes
  rtc: HTMLAttributes
  ruby: HTMLAttributes
  s: HTMLAttributes
  samp: HTMLAttributes
  script: HTMLAttributes
  section: HTMLAttributes
  select: HTMLAttributes
  slot: HTMLAttributes
  small: HTMLAttributes
  source: HTMLAttributes
  span: HTMLAttributes
  strong: HTMLAttributes
  style: HTMLAttributes
  sub: HTMLAttributes
  summary: HTMLAttributes
  sup: HTMLAttributes
  svg: HTMLAttributes
  table: HTMLAttributes
  tbody: HTMLAttributes
  td: HTMLAttributes
  template: HTMLAttributes
  textarea: HTMLAttributes
  tfoot: HTMLAttributes
  th: HTMLAttributes
  thead: HTMLAttributes
  time: HTMLAttributes
  title: HTMLAttributes
  tr: HTMLAttributes
  track: HTMLAttributes
  u: HTMLAttributes
  ul: HTMLAttributes
  var: HTMLAttributes
  video: HTMLAttributes
  wbr: HTMLAttributes
}

interface Element<P = any> {
  type: string
  props: P
}

export { Element, HTMLAttributes, IntrinsicElements }
